### ISSUE TITLE
Does not launch on MacOS

### ISSUE THREAD

**Issue by lambtho12** [notpushkin/Mailspring-Libre#37]
Windows and MacOS builds have actually already been added to travis, just not yet to releases. Travis upload them to catbox.moe when done.

Latest Windows:
https://files.catbox.moe/wn3rbc.msi
Latest MacOs:
https://files.catbox.moe/6o27qn.zip

Originally posted by @louis-lau in #1 

------------
I just tried to install mailspring-libre on MacOS 10.15.5 and it just won't launch properly. I had no issue with the original mailspring.

It looks like the app is active as it appears in the dock and menu bar is accessible, but there is no window at all.
The menu items do not work either, except for the "calendar preview" and "run with debug flags" under "Developer".

When I click on `Developer > Run with Debug Flags`, the app restarts in debug mode and this time it seems to work properly. 
I did the onboarding with a new account and tested a bit, everything seemed fine with debug flags enable. If I deactivate debug flags, the app reboots and once again the window does not appear.

Here is the output of running `/Applications/Mailspring.app/Contents/MacOS/Mailspring --enable-logging`

<details>
 <summary>Console output</summary>

```console
Running database migrations
App load time: 275ms

{"error":null}
2020-07-01 15:09:24.619 Mailspring[3317:136941] *** WARNING: Textured window <AtomNSWindow: 0x7fe7e8117110> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
Error Downloading Update: Could not get code signature for running application
Error Downloading Update: Could not get code signature for running application
[3317:0701/150925.562629:INFO:CONSOLE(16)] "Window load time: 562ms", source: file:///Applications/Mailspring.app/Contents/Resources/app.asar/static/index.js (16)
[3317:0701/150925.564558:INFO:CONSOLE(16)] "Window load time: 559ms", source: file:///Applications/Mailspring.app/Contents/Resources/app.asar/static/index.js (16)
[3317:0701/150928.159815:INFO:CONSOLE(181)] "Error: Cannot find component for page: authenticate", source: /Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js (181)
{ Error: Cannot find component for page: authenticate
    at OnboardingRoot.render (file:///var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/nylas-build/electron-packager/darwin-x64/Mailspring-darwin-x64/Electron.app/Contents/Resources/app/internal_packages/onboarding/lib/onboarding-root.tsx:71:13)
    at ah (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:163:192)
    at $g (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:162:264)
    at eh (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:171:13)
    at ai (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:202:255)
    at bi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:203:271)
    at Fi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:218:174)
    at Gi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:174)
    at ii (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:214:252)
    at xg (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:212:94)
    at Object.enqueueSetState (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:133:223)
    at InjectedComponentSet.Component.setState (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:373:16)
    at ComponentRegistry._componentUnlistener.mailspring_exports_1.ComponentRegistry.listen (file:///var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/nylas-build/electron-packager/darwin-x64/Mailspring-darwin-x64/Electron.app/Contents/Resources/app/src/components/injected-component-set.tsx:114:12)
    at EventEmitter.eventHandler (file:///var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/nylas-build/electron-packager/darwin-x64/Mailspring-darwin-x64/Electron.app/Contents/Resources/app/src/global/mailspring-store.ts:128:23)
    at EventEmitter.emit (events.js:187:15)
    at EventEmitter.emit (domain.js:442:20)
    at ComponentRegistry.trigger (file:///var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/nylas-build/electron-packager/darwin-x64/Mailspring-darwin-x64/Electron.app/Contents/Resources/app/src/global/mailspring-store.ts:141:26)
    at ComponentRegistry.triggerDebounced.underscore_1.default.debounce (file:///var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/nylas-build/electron-packager/darwin-x64/Mailspring-darwin-x64/Electron.app/Contents/Resources/app/src/registries/component-registry.ts:197:44)
    at later (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/underscore/underscore.js:828:25) message: 'Cannot find component for page: authenticate' } { pluginIds: [ 'onboarding' ] }
[3317:0701/150928.184434:INFO:CONSOLE(101)] "Error: Cannot find component for page: authenticate", source: /Applications/Mailspring.app/Contents/Resources/app.asar/src/error-logger.js (101)
[3317:0701/150928.184581:INFO:CONSOLE(181)] "Error: Cannot find component for page: authenticate", source: /Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js (181)
{ Error: Cannot find component for page: authenticate
    at OnboardingRoot.render (file:///var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/nylas-build/electron-packager/darwin-x64/Mailspring-darwin-x64/Electron.app/Contents/Resources/app/internal_packages/onboarding/lib/onboarding-root.tsx:71:13)
    at ah (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:163:192)
    at $g (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:162:264)
    at eh (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:171:13)
    at ai (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:202:255)
    at bi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:203:271)
    at Fi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:218:174)
    at Gi (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:174)
    at ii (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:214:252)
    at xg (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:212:94)
    at Object.enqueueSetState (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:133:223)
    at InjectedComponentSet.Component.setState (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react/cjs/react.development.js:373:16)
    at ComponentRegistry._componentUnlistener.mailspring_exports_1.ComponentRegistry.listen (file:///var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/nylas-build/electron-packager/darwin-x64/Mailspring-darwin-x64/Electron.app/Contents/Resources/app/src/components/injected-component-set.tsx:114:12)
    at EventEmitter.eventHandler (file:///var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/nylas-build/electron-packager/darwin-x64/Mailspring-darwin-x64/Electron.app/Contents/Resources/app/src/global/mailspring-store.ts:128:23)
    at EventEmitter.emit (events.js:187:15)
    at EventEmitter.emit (domain.js:442:20)
    at ComponentRegistry.trigger (file:///var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/nylas-build/electron-packager/darwin-x64/Mailspring-darwin-x64/Electron.app/Contents/Resources/app/src/global/mailspring-store.ts:141:26)
    at ComponentRegistry.triggerDebounced.underscore_1.default.debounce (file:///var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/nylas-build/electron-packager/darwin-x64/Mailspring-darwin-x64/Electron.app/Contents/Resources/app/src/registries/component-registry.ts:197:44)
    at later (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/underscore/underscore.js:828:25) message: 'Cannot find component for page: authenticate' } { url:
   '/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js',
  line: 217,
  column: 372,
  pluginIds: [ 'onboarding' ] }
[3317:0701/150928.188426:INFO:CONSOLE(101)] "Error: Cannot find component for page: authenticate", source: /Applications/Mailspring.app/Contents/Resources/app.asar/src/error-logger.js (101)
[3317:0701/150928.188505:INFO:CONSOLE(217)] "Uncaught Error: Cannot find component for page: authenticate", source: /Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js (217)
Raven: 429 - undefined
Raven: 429 - undefined

```
</details>

**Comment by exprez135** [comment]
Hello! Thanks for the report. If you could, try the most recent release (1.7.8-libre) and let us know if you still have any problems. If not, feel free to close this issue.
